--
-- PostgreSQL database dump
--

-- Dumped from database version 16.1
-- Dumped by pg_dump version 16.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: copycustomer; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.copycustomer (
    id integer NOT NULL,
    name character varying(100),
    email character varying(100),
    phone character varying(12),
    address character varying(255),
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);


ALTER TABLE public.copycustomer OWNER TO postgres;

--
-- Name: copyCustomer_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.copycustomer ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."copyCustomer_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: customers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.customers (
    id integer NOT NULL,
    name character varying(100),
    email character varying(100),
    phone character varying(12),
    password character varying(100),
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);


ALTER TABLE public.customers OWNER TO postgres;

--
-- Name: customers_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.customers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: orders; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.orders (
    id integer NOT NULL,
    customers_id integer,
    total_quantity integer,
    status character varying(20),
    time_order date,
    last_updated date
);


ALTER TABLE public.orders OWNER TO postgres;

--
-- Name: orders_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: productdetails; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.productdetails (
    id integer NOT NULL,
    order_id integer,
    product_id integer,
    product_code character varying(255),
    product_quantity integer,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);


ALTER TABLE public.productdetails OWNER TO postgres;

--
-- Name: productDetails_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.productdetails ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."productDetails_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.products (
    id integer NOT NULL,
    product_name character varying(255),
    product_price money,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);


ALTER TABLE public.products OWNER TO postgres;

--
-- Name: products_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: copycustomer; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.copycustomer (id, name, email, phone, address, created_at, updated_at) FROM stdin;
1	Nguyễn Cường	cuong1@gmail.com	0912345678	Hà Nội	2024-01-07 22:23:19.769796+07	2024-01-07 22:23:19.769796+07
2	Cường Nguyễn	cuong2@gmail.com	0123456789	Hà Nội	2024-01-07 22:23:57.603556+07	2024-01-07 22:23:57.603556+07
3	Quang Cường	cuong3@gmail.com	0913245688	Hà Nội	2024-01-07 22:24:26.766522+07	2024-01-07 22:24:26.766522+07
\.


--
-- Data for Name: customers; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.customers (id, name, email, phone, password, created_at, updated_at) FROM stdin;
1	Nguyễn Cường	cuong1@gmail.com	0912345678	12345678	2024-01-07 18:05:53.280346+07	2024-01-07 18:05:53.280346+07
2	Cường Nguyễn	cuong2@gmail.com	0123456789	123456789	2024-01-07 18:06:59.257563+07	2024-01-07 18:06:59.257563+07
3	Quang Cường	cuong3@gmail.com	0913245688	1234567890	2024-01-07 18:07:41.974331+07	2024-01-07 18:07:41.974331+07
\.


--
-- Data for Name: orders; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.orders (id, customers_id, total_quantity, status, time_order, last_updated) FROM stdin;
1	1	2	shipped	2023-01-06	2023-01-07
2	2	2	shipping	2023-01-06	2023-01-08
3	3	2	cancelled	2023-01-06	2023-01-07
\.


--
-- Data for Name: productdetails; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.productdetails (id, order_id, product_id, product_code, product_quantity, created_at, updated_at) FROM stdin;
1	1	1	'A'	2	2024-01-07 22:38:54.516508+07	2024-01-07 22:38:54.516508+07
2	2	2	'B'	2	2024-01-07 22:39:25.386916+07	2024-01-07 22:39:25.386916+07
3	3	3	'C'	2	2024-01-07 22:39:25.386916+07	2024-01-07 22:39:25.386916+07
\.


--
-- Data for Name: products; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.products (id, product_name, product_price, created_at, updated_at) FROM stdin;
1	Khóa học HTML CSS Pro	$1,000,000.00	2024-01-07 22:31:06.664518+07	2024-01-07 22:31:06.664518+07
2	Khóa học JS Pro	$1,200,000.00	2024-01-07 22:31:06.664518+07	2024-01-07 22:31:06.664518+07
3	Khóa học Front-end	$5,000,000.00	2024-01-07 22:31:06.664518+07	2024-01-07 22:31:06.664518+07
\.


--
-- Name: copyCustomer_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."copyCustomer_id_seq"', 1, false);


--
-- Name: customers_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.customers_id_seq', 1, false);


--
-- Name: orders_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.orders_id_seq', 1, false);


--
-- Name: productDetails_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."productDetails_id_seq"', 1, false);


--
-- Name: products_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.products_id_seq', 3, true);


--
-- Name: copycustomer copyCustomer_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.copycustomer
    ADD CONSTRAINT "copyCustomer_pkey" PRIMARY KEY (id);


--
-- Name: customers customers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT customers_pkey PRIMARY KEY (id);


--
-- Name: orders orders_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id);


--
-- Name: productdetails productDetails_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.productdetails
    ADD CONSTRAINT "productDetails_pkey" PRIMARY KEY (id);


--
-- Name: products products_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (id);


--
-- Name: orders orders_customers_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_customers_id_fkey FOREIGN KEY (customers_id) REFERENCES public.copycustomer(id);


--
-- Name: productdetails productDetails_order_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.productdetails
    ADD CONSTRAINT "productDetails_order_id_fkey" FOREIGN KEY (order_id) REFERENCES public.orders(id);


--
-- Name: productdetails productDetails_product_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.productdetails
    ADD CONSTRAINT "productDetails_product_id_fkey" FOREIGN KEY (product_id) REFERENCES public.products(id);


--
-- PostgreSQL database dump complete
--

